#!usr/bin/env zsh

echo "Linking themes"
ln -sf $PWD/gnome-configs/themes ~/.themes

echo "Linking Icons"
ln -sf $PWD/gnome-configs/icons ~/.icons

echo "Loading Settings"
dconf load -f / < $PWD/gnome-configs/settings.ini
