#!usr/bin/env zsh

echo "Installing NVIM"
sudo dnf install nvim

echo "Installing Neofetch"
sudo dnf install neofetch

echo "Linking themes"
ln -sf $PWD/gnome-configs/themes ~/.themes

echo "Linking Icons"
ln -sf $PWD/gnome-configs/icons ~/.icons

echo "Loading Settings"
dconf load -f / < $PWD/gnome-configs/settings.ini
