#!/usr/bin/env zsh

echo "Linking vimrc with ./vimrc"
echo "Linking zshrc with ./zshrc"
echo "Linking p10k.zsh with ~/.p10k.zsh"

ln -sf $PWD/vimrc ~/.vimrc
ln -sf $PWD/zshrc ~/.zshrc
ln -sf $PWD/p10k.zsh ~/.p10k.zsh

NVIMPATH=(command -v nvim)

if [ [$NVIMPATH != ""] ] 
then
  echo "Linking nvim with ~/.config/nvim"
  ln -sf $PWD/nvim ~/.config/nvim
else
    echo "Neovim not found"
fi
