#!/usr/bin/env zsh

echo "Linking vimrc with ~/.vimrc"
echo "Linking .vim with ~/.vim"
echo "Linking zshrc with ~/.zshrc"
echo "Linking zsh.aliases with ~/.zsh.aliases"
echo "Linking p10k.zsh with ~/.p10k.zsh"
echo "Linking p10kFull.zsh with ~/.p10kFull.zsh"

ln -sf $PWD/vimrc ~/.vimrc
ln -sf $PWD/.vim ~/
ln -sf $PWD/zshrc ~/.zshrc
ln -sf $PWD/zsh.aliases ~/.zsh.aliases
ln -sf $PWD/p10k.zsh ~/.p10k.zsh
ln -sf $PWD/p10kFull.zsh ~/.p10kFull.zsh


if [[ -r "${HOME}/.config/nvim" ]] 
then
  echo "Linking nvim with ~/.config/nvim"
  ln -sf $PWD/nvim ~/.config/nvim
else
    echo "Neovim not found"
fi
